name: Run API Collection

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  run-collection:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run collection
        run: postman collection run collection.json
