name: Automated API tests using Postman CLI

on:
  workflow_dispatch:
  push:
  schedule:
    #- cron: '*/15 * * * *'   
    # Every 15 minutes (UTC)

jobs:
  automated-api-tests:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      - uses: actions/checkout@v4

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "56639983-7d72ec11-0b96-4fe5-aa76-315f18ed523d"
